'use client'

import { useState } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { db } from '@/lib/db'
import { patient, getDaysSinceSurgery, getWeeksSinceSurgery, getCurrentPhase } from '@/data/patient'
import { phases } from '@/data/phases'
import { useStreak } from '@/hooks/use-streak'
import { useRecoveryScore } from '@/hooks/use-recovery-score'
import { FileText, Printer } from '@phosphor-icons/react'

type Lang = 'ru' | 'en' | 'tr'

const translations = {
  ru: {
    pageTitle: 'Отчёт для врача',
    print: 'Печать',
    reportTitle: 'Отчёт о реабилитации',
    sectionPatient: 'Пациент',
    name: 'Имя:',
    age: 'Возраст:',
    surgery: 'Операция:',
    week: 'Неделя:',
    operatedArm: 'Оперированная рука:',
    right: 'Правая',
    left: 'Левая',
    dayLabel: 'день',
    yearLabel: 'лет',
    sectionROM: 'Амплитуда движений (ROM)',
    lastMeasure: 'Последний замер:',
    flexion: 'Сгибание:',
    extensionDeficit: 'Дефицит разгибания:',
    arc: 'Дуга (Arc):',
    pronation: 'Пронация:',
    supination: 'Супинация:',
    bestResult: 'Лучший результат:',
    noMeasures: 'Нет замеров',
    sectionActivity: 'Активность (30 дней)',
    sessionsCompleted: 'Сессий выполнено:',
    activeDaysOf: 'Активных дней:',
    of: 'из',
    currentStreak: 'Текущий стрик:',
    days: 'дней',
    recoveryScore: 'Recovery Score сегодня:',
    sectionPainSleep: 'Боль и сон (30 дней)',
    avgPain: 'Средняя боль:',
    avgSleep: 'Средний сон:',
    perNight: 'ч/ночь',
    na: 'н/д',
    sectionROMHistory: 'История замеров ROM',
    colDate: 'Дата',
    colFlexion: 'Сгиб.',
    colExtDef: 'Деф. разг.',
    generatedBy: 'Сгенерировано приложением Elbow Recovery',
    locale: 'ru-RU',
  },
  en: {
    pageTitle: 'Doctor Report',
    print: 'Print',
    reportTitle: 'Rehabilitation Report',
    sectionPatient: 'Patient',
    name: 'Name:',
    age: 'Age:',
    surgery: 'Surgery:',
    week: 'Week:',
    operatedArm: 'Operated Arm:',
    right: 'Right',
    left: 'Left',
    dayLabel: 'day',
    yearLabel: 'y.o.',
    sectionROM: 'Range of Motion (ROM)',
    lastMeasure: 'Last Measurement:',
    flexion: 'Flexion:',
    extensionDeficit: 'Extension Deficit:',
    arc: 'Arc:',
    pronation: 'Pronation:',
    supination: 'Supination:',
    bestResult: 'Best Result:',
    noMeasures: 'No measurements',
    sectionActivity: 'Activity (30 days)',
    sessionsCompleted: 'Sessions completed:',
    activeDaysOf: 'Active days:',
    of: 'of',
    currentStreak: 'Current streak:',
    days: 'days',
    recoveryScore: 'Recovery Score today:',
    sectionPainSleep: 'Pain & Sleep (30 days)',
    avgPain: 'Avg. pain:',
    avgSleep: 'Avg. sleep:',
    perNight: 'hrs/night',
    na: 'n/a',
    sectionROMHistory: 'ROM Measurement History',
    colDate: 'Date',
    colFlexion: 'Flex.',
    colExtDef: 'Ext.Def.',
    generatedBy: 'Generated by Elbow Recovery App',
    locale: 'en-US',
  },
  tr: {
    pageTitle: 'Doktor Raporu',
    print: 'Yazdır',
    reportTitle: 'Rehabilitasyon Raporu',
    sectionPatient: 'Hasta',
    name: 'Ad:',
    age: 'Yaş:',
    surgery: 'Ameliyat:',
    week: 'Hafta:',
    operatedArm: 'Ameliyatlı Kol:',
    right: 'Sağ',
    left: 'Sol',
    dayLabel: 'gün',
    yearLabel: 'yaş',
    sectionROM: 'Hareket Açıklığı (ROM)',
    lastMeasure: 'Son Ölçüm:',
    flexion: 'Fleksiyon:',
    extensionDeficit: 'Ekstansiyon Açığı:',
    arc: 'Ark:',
    pronation: 'Pronasyon:',
    supination: 'Supinasyon:',
    bestResult: 'En İyi Sonuç:',
    noMeasures: 'Ölçüm yok',
    sectionActivity: 'Aktivite (30 gün)',
    sessionsCompleted: 'Tamamlanan seans:',
    activeDaysOf: 'Aktif gün:',
    of: '/',
    currentStreak: 'Mevcut seri:',
    days: 'gün',
    recoveryScore: 'Bugün Recovery Score:',
    sectionPainSleep: 'Ağrı ve Uyku (30 gün)',
    avgPain: 'Ort. ağrı:',
    avgSleep: 'Ort. uyku:',
    perNight: 'sa/gece',
    na: 'yok',
    sectionROMHistory: 'ROM Ölçüm Geçmişi',
    colDate: 'Tarih',
    colFlexion: 'Flek.',
    colExtDef: 'Eks.Aç.',
    generatedBy: 'Elbow Recovery Uygulaması tarafından oluşturuldu',
    locale: 'tr-TR',
  },
}

export default function DoctorReportPage() {
  const [lang, setLang] = useState<Lang>('ru')
  const t = translations[lang]

  const days = getDaysSinceSurgery()
  const weeks = getWeeksSinceSurgery()
  const phaseNum = getCurrentPhase()
  const phase = phases.find(p => p.number === phaseNum)
  const { streak, totalSessions, activeDays } = useStreak()
  const score = useRecoveryScore()
  const today = new Date().toISOString().split('T')[0]

  const since30 = (() => { const d = new Date(); d.setDate(d.getDate() - 30); return d.toISOString().split('T')[0] })()

  const recentROMs = useLiveQuery(
    () => db.romMeasurements.orderBy('date').reverse().limit(5).toArray()
  )
  const recentPain = useLiveQuery(
    () => db.painEntries.where('date').between(since30, today, true, true).toArray(),
    [since30, today]
  )
  const recentSleep = useLiveQuery(
    () => db.sleepLogs.where('date').between(since30, today, true, true).toArray(),
    [since30, today]
  )
  const recentSessions = useLiveQuery(
    () => db.exerciseSessions.where('date').between(since30, today, true, true).toArray(),
    [since30, today]
  )

  const avgPainVal = recentPain && recentPain.length > 0
    ? (recentPain.reduce((s, p) => s + p.level, 0) / recentPain.length).toFixed(1)
    : null

  const avgSleepVal = recentSleep && recentSleep.length > 0
    ? (recentSleep.reduce((s, l) => s + l.totalHours, 0) / recentSleep.length).toFixed(1)
    : null

  const sessionsLast30 = recentSessions?.length ?? 0
  const activeDaysLast30 = new Set(recentSessions?.map(s => s.date) ?? []).size

  const latestROM = recentROMs?.[0]
  const bestROM = recentROMs && recentROMs.length > 0
    ? recentROMs.reduce((best, r) => r.arc > best.arc ? r : best, recentROMs[0])
    : null

  const handlePrint = () => { window.print() }

  const reportDate = new Date().toLocaleDateString(t.locale, { day: 'numeric', month: 'long', year: 'numeric' })

  return (
    <div className="py-6" style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 10 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <FileText size={28} weight="duotone" style={{ color: 'var(--color-primary)' }} />
          <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 'var(--text-3xl)', fontWeight: 600 }}>
            {t.pageTitle}
          </h1>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          {/* Language toggle */}
          <div style={{ display: 'flex', gap: 3, backgroundColor: 'var(--color-surface-alt)', borderRadius: 'var(--radius-full)', padding: 3 }}>
            {(['ru', 'en', 'tr'] as const).map(l => (
              <button
                key={l}
                onClick={() => setLang(l)}
                style={{
                  padding: '5px 10px',
                  borderRadius: 'var(--radius-full)',
                  border: 'none',
                  fontSize: 11,
                  fontWeight: 700,
                  cursor: 'pointer',
                  backgroundColor: lang === l ? 'var(--color-primary)' : 'transparent',
                  color: lang === l ? '#fff' : 'var(--color-text-muted)',
                  textTransform: 'uppercase',
                  letterSpacing: '0.04em',
                  transition: 'all 0.15s ease',
                }}
              >
                {l.toUpperCase()}
              </button>
            ))}
          </div>
          {/* Print */}
          <button
            onClick={handlePrint}
            style={{
              display: 'flex', alignItems: 'center', gap: 6,
              padding: '10px 16px', borderRadius: 'var(--radius-full)',
              backgroundColor: 'var(--color-primary)', color: '#fff',
              border: 'none', fontSize: 'var(--text-sm)', fontWeight: 600, cursor: 'pointer',
            }}
          >
            <Printer size={16} weight="bold" />
            {t.print}
          </button>
        </div>
      </div>

      {/* Report content */}
      <div id="doctor-report" style={{
        padding: 24, borderRadius: 'var(--radius-lg)',
        backgroundColor: 'var(--color-surface)', border: '1px solid var(--color-border)',
        boxShadow: 'var(--shadow-sm)',
      }}>
        <div style={{ textAlign: 'center', marginBottom: 24, paddingBottom: 16, borderBottom: '1px solid var(--color-border)' }}>
          <h2 style={{ fontFamily: 'var(--font-display)', fontSize: 'var(--text-xl)', fontWeight: 600, margin: '0 0 4px' }}>
            {t.reportTitle}
          </h2>
          <p style={{ fontSize: 'var(--text-sm)', color: 'var(--color-text-muted)', margin: 0 }}>{reportDate}</p>
        </div>

        {/* Patient info */}
        <section style={{ marginBottom: 20 }}>
          <h3 style={{ fontSize: 'var(--text-sm)', fontWeight: 600, color: 'var(--color-text)', marginBottom: 8, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
            {t.sectionPatient}
          </h3>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '6px 16px', fontSize: 'var(--text-sm)' }}>
            <span style={{ color: 'var(--color-text-muted)' }}>{t.name}</span>
            <span style={{ fontWeight: 500 }}>{patient.name}</span>
            <span style={{ color: 'var(--color-text-muted)' }}>{t.age}</span>
            <span style={{ fontWeight: 500 }}>{patient.age} {t.yearLabel}</span>
            <span style={{ color: 'var(--color-text-muted)' }}>{t.surgery}</span>
            <span style={{ fontWeight: 500 }}>{patient.surgeryDate} ({t.dayLabel} {days})</span>
            <span style={{ color: 'var(--color-text-muted)' }}>{t.week}</span>
            <span style={{ fontWeight: 500 }}>{weeks} ({phase?.name})</span>
            <span style={{ color: 'var(--color-text-muted)' }}>{t.operatedArm}</span>
            <span style={{ fontWeight: 500 }}>{patient.targetArm === 'right' ? t.right : t.left}</span>
          </div>
        </section>

        {/* ROM */}
        <section style={{ marginBottom: 20 }}>
          <h3 style={{ fontSize: 'var(--text-sm)', fontWeight: 600, color: 'var(--color-text)', marginBottom: 8, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
            {t.sectionROM}
          </h3>
          {latestROM ? (
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '6px 16px', fontSize: 'var(--text-sm)' }}>
              <span style={{ color: 'var(--color-text-muted)' }}>{t.lastMeasure}</span>
              <span style={{ fontWeight: 500 }}>{latestROM.date}</span>
              <span style={{ color: 'var(--color-text-muted)' }}>{t.flexion}</span>
              <span style={{ fontWeight: 600, color: 'var(--color-primary)' }}>{latestROM.flexion}°</span>
              <span style={{ color: 'var(--color-text-muted)' }}>{t.extensionDeficit}</span>
              <span style={{ fontWeight: 500 }}>{latestROM.extensionDeficit}°</span>
              <span style={{ color: 'var(--color-text-muted)' }}>{t.arc}</span>
              <span style={{ fontWeight: 600, color: 'var(--color-primary)' }}>{latestROM.arc}°</span>
              {latestROM.pronation != null && (
                <>
                  <span style={{ color: 'var(--color-text-muted)' }}>{t.pronation}</span>
                  <span style={{ fontWeight: 500 }}>{latestROM.pronation}°</span>
                </>
              )}
              {latestROM.supination != null && (
                <>
                  <span style={{ color: 'var(--color-text-muted)' }}>{t.supination}</span>
                  <span style={{ fontWeight: 500 }}>{latestROM.supination}°</span>
                </>
              )}
              {bestROM && bestROM.arc > latestROM.arc && (
                <>
                  <span style={{ color: 'var(--color-text-muted)' }}>{t.bestResult}</span>
                  <span style={{ fontWeight: 500 }}>{bestROM.arc}° ({bestROM.date})</span>
                </>
              )}
            </div>
          ) : (
            <p style={{ fontSize: 'var(--text-sm)', color: 'var(--color-text-muted)' }}>{t.noMeasures}</p>
          )}
        </section>

        {/* Activity */}
        <section style={{ marginBottom: 20 }}>
          <h3 style={{ fontSize: 'var(--text-sm)', fontWeight: 600, color: 'var(--color-text)', marginBottom: 8, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
            {t.sectionActivity}
          </h3>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '6px 16px', fontSize: 'var(--text-sm)' }}>
            <span style={{ color: 'var(--color-text-muted)' }}>{t.sessionsCompleted}</span>
            <span style={{ fontWeight: 500 }}>{sessionsLast30}</span>
            <span style={{ color: 'var(--color-text-muted)' }}>{t.activeDaysOf}</span>
            <span style={{ fontWeight: 500 }}>{activeDaysLast30} {t.of} 30</span>
            <span style={{ color: 'var(--color-text-muted)' }}>{t.currentStreak}</span>
            <span style={{ fontWeight: 500 }}>{streak} {t.days}</span>
            <span style={{ color: 'var(--color-text-muted)' }}>{t.recoveryScore}</span>
            <span style={{ fontWeight: 600, color: 'var(--color-primary)' }}>{score.total}/100</span>
          </div>
        </section>

        {/* Pain & Sleep */}
        <section style={{ marginBottom: 20 }}>
          <h3 style={{ fontSize: 'var(--text-sm)', fontWeight: 600, color: 'var(--color-text)', marginBottom: 8, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
            {t.sectionPainSleep}
          </h3>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '6px 16px', fontSize: 'var(--text-sm)' }}>
            <span style={{ color: 'var(--color-text-muted)' }}>{t.avgPain}</span>
            <span style={{ fontWeight: 500 }}>{avgPainVal !== null ? `${avgPainVal}/10` : t.na}</span>
            <span style={{ color: 'var(--color-text-muted)' }}>{t.avgSleep}</span>
            <span style={{ fontWeight: 500 }}>{avgSleepVal !== null ? `${avgSleepVal} ${t.perNight}` : t.na}</span>
          </div>
        </section>

        {/* ROM History */}
        {recentROMs && recentROMs.length > 1 && (
          <section>
            <h3 style={{ fontSize: 'var(--text-sm)', fontWeight: 600, color: 'var(--color-text)', marginBottom: 8, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
              {t.sectionROMHistory}
            </h3>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 'var(--text-sm)' }}>
              <thead>
                <tr style={{ borderBottom: '1px solid var(--color-border)' }}>
                  <th style={{ padding: '6px 8px', textAlign: 'left', color: 'var(--color-text-muted)', fontWeight: 500 }}>{t.colDate}</th>
                  <th style={{ padding: '6px 8px', textAlign: 'right', color: 'var(--color-text-muted)', fontWeight: 500 }}>{t.colFlexion}</th>
                  <th style={{ padding: '6px 8px', textAlign: 'right', color: 'var(--color-text-muted)', fontWeight: 500 }}>{t.colExtDef}</th>
                  <th style={{ padding: '6px 8px', textAlign: 'right', color: 'var(--color-text-muted)', fontWeight: 500 }}>Arc</th>
                </tr>
              </thead>
              <tbody>
                {recentROMs.map(rom => (
                  <tr key={rom.id} style={{ borderBottom: '1px solid var(--color-border)' }}>
                    <td style={{ padding: '6px 8px' }}>{rom.date}</td>
                    <td style={{ padding: '6px 8px', textAlign: 'right', fontWeight: 500 }}>{rom.flexion}°</td>
                    <td style={{ padding: '6px 8px', textAlign: 'right' }}>{rom.extensionDeficit}°</td>
                    <td style={{ padding: '6px 8px', textAlign: 'right', fontWeight: 600, color: 'var(--color-primary)' }}>{rom.arc}°</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>
        )}

        {/* Footer */}
        <div style={{ marginTop: 24, paddingTop: 16, borderTop: '1px solid var(--color-border)', textAlign: 'center' }}>
          <p style={{ fontSize: 11, color: 'var(--color-text-muted)' }}>
            {t.generatedBy} | {reportDate}
          </p>
        </div>
      </div>
    </div>
  )
}
